import 'package:care_circle/core/models/care_circle_models.dart';

class CareCircleMockService {
  bool _vitalsIncident =
      false; // mirrors incident-state.json; toggle in debug menu if needed
  static final List<Resident> _residents = [
    Resident(
      id: 'resident-meera',
      name: 'Meera Kapoor',
      avatarInitials: 'MK',
      relationship: 'Mother',
      facility: const Facility(
        id: 'gurugram-01',
        name: 'CareCircle Aravalli',
        city: 'Gurugram',
      ),
      timezone: 'Asia/Kolkata',
      sharingPreferences: const SharingPreferences(
        shareMedicationStatus: true,
        shareMealStatus: true,
        shareActivityDetails: true,
        shareVitalDetails: false,
        shareStaffNotes: 'limited',
        sharePhotos: false,
      ),
    ),
    Resident(
      id: 'resident-devendra',
      name: 'Devendra Kapoor',
      avatarInitials: 'DK',
      relationship: 'Father',
      facility: const Facility(
        id: 'pune-02',
        name: 'CareCircle Sahyadri',
        city: 'Pune',
      ),
      timezone: 'Asia/Kolkata',
      sharingPreferences: const SharingPreferences(
        shareMedicationStatus: true,
        shareMealStatus: false,
        shareActivityDetails: true,
        shareVitalDetails: true,
        shareStaffNotes: 'none',
        sharePhotos: true,
      ),
    ),
    // --- Additional residents ---
    Resident(
      id: 'resident-anjali',
      name: 'Anjali Deshpande',
      avatarInitials: 'AD',
      relationship: 'Mother-in-law',
      facility: const Facility(
        id: 'pune-02',
        name: 'CareCircle Sahyadri',
        city: 'Pune',
      ),
      timezone: 'Asia/Kolkata',
      sharingPreferences: const SharingPreferences(
        shareMedicationStatus: true,
        shareMealStatus: true,
        shareActivityDetails: true,
        shareVitalDetails: true,
        shareStaffNotes: 'full',
        sharePhotos: true,
      ),
    ),
    Resident(
      id: 'resident-rajan',
      name: 'Rajan Iyer',
      avatarInitials: 'RI',
      relationship: 'Father-in-law',
      facility: const Facility(
        id: 'gurugram-01',
        name: 'CareCircle Aravalli',
        city: 'Gurugram',
      ),
      timezone: 'Asia/Kolkata',
      sharingPreferences: const SharingPreferences(
        shareMedicationStatus: true,
        shareMealStatus: false,
        shareActivityDetails: false,
        shareVitalDetails: false,
        shareStaffNotes: 'none',
        sharePhotos: false,
      ),
    ),
  ];

  static final List<DailySummary> _summaries = [
    // --- Meera: 3-week window ---
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-19',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-19T05:10:00.000Z'),
      headline: 'Meera has had a settled morning.',
      highlights: const [
        'Breakfast recorded',
        'Morning medication recorded',
        'Joined the garden walk',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-18',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-18T05:05:00.000Z'),
      headline: 'A calm day with good appetite.',
      highlights: const [
        'Finished breakfast and lunch',
        'Attended bhajan session',
        'Evening medication on time',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-17',
      reassuranceState: ReassuranceState.needsAttention,
      generatedAt: DateTime.parse('2026-09-17T05:20:00.000Z'),
      headline: 'Meera reported mild knee discomfort.',
      highlights: const [
        'Physiotherapy adjusted',
        'Pain noted as 3/10',
        'Stayed indoors in the afternoon',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-16',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-16T05:00:00.000Z'),
      headline: 'Steady day, good social participation.',
      highlights: const [
        'Art & craft session',
        'Ate full meals',
        'Slept well per night log',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-15',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-15T05:15:00.000Z'),
      headline: 'Enjoyed the morning walk and music hour.',
      highlights: const [
        'Garden walk 20 min',
        'Music therapy attended',
        'Hydration reminders completed',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-14',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-14T05:00:00.000Z'),
      headline: 'Limited updates recorded for Meera.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-13',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-13T05:10:00.000Z'),
      headline: 'Good day with family video call.',
      highlights: const [
        'Video call with son',
        'Lunch completed',
        'Afternoon rest 90 min',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-12',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-12T05:05:00.000Z'),
      headline: 'Active morning, quiet afternoon.',
      highlights: const [
        'Group stretching',
        'Breakfast well eaten',
        'Evening tea with peers',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-11',
      reassuranceState: ReassuranceState.needsAttention,
      generatedAt: DateTime.parse('2026-09-11T05:25:00.000Z'),
      headline: 'Slight rise in blood pressure noted.',
      highlights: const [
        'BP 138/86 at 09:15',
        'Rechecked at 11:00 — 132/82',
        'Doctor informed as precaution',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-10',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-10T05:00:00.000Z'),
      headline: 'Routine day, all meals completed.',
      highlights: const [
        'Breakfast, lunch, dinner completed',
        'Medication on schedule',
        'Short walk in the corridor',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-09',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-09T05:10:00.000Z'),
      headline: 'Cheerful day, enjoyed the festival decoration.',
      highlights: const [
        'Helped decorate common area',
        'Ate festive sweets in moderation',
        'Evening medication taken',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-08',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-08T05:05:00.000Z'),
      headline: 'Calm and settled.',
      highlights: const [
        'Breakfast recorded',
        'Physiotherapy 25 min',
        'Nap 45 min',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-07',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-07T05:00:00.000Z'),
      headline: 'Very few updates logged today.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-06',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-06T05:15:00.000Z'),
      headline: 'Good energy, enjoyed the garden.',
      highlights: const [
        'Garden walk 30 min',
        'Lunch full portion',
        'Read in the library',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-05',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-05T05:10:00.000Z'),
      headline: 'Settled day with visitors.',
      highlights: const [
        'Daughter visited in the afternoon',
        'Snacks taken',
        'Evening medication on time',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-04',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-04T05:05:00.000Z'),
      headline: 'Routine day.',
      highlights: const [
        'All meals completed',
        'Group activity attended',
        'Hydration reminders done',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-03',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-03T05:00:00.000Z'),
      headline: 'Quiet but content.',
      highlights: const [
        'Breakfast recorded',
        'Afternoon rest',
        'Short corridor walk',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-02',
      reassuranceState: ReassuranceState.needsAttention,
      generatedAt: DateTime.parse('2026-09-02T05:20:00.000Z'),
      headline: 'Mild dehydration signs; fluids encouraged.',
      highlights: const [
        'Fluids increased through the day',
        'Urine output monitored',
        'Evening check stable',
      ],
    ),
    DailySummary(
      residentId: 'resident-meera',
      localDate: '2026-09-01',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-01T05:10:00.000Z'),
      headline: 'Good start to the month.',
      highlights: const [
        'Breakfast and lunch completed',
        'Music hour attended',
        'Medication on schedule',
      ],
    ),

    // --- Devendra: 3-week window ---
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-19',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-18T14:30:00.000Z'),
      headline: 'There are only a few updates for Devendra today.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-18',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-18T05:15:00.000Z'),
      headline: 'Physiotherapy completed, mood stable.',
      highlights: const [
        'Physiotherapy 30 min',
        'Morning medication taken',
        'Heart rate within range',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-17',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-17T05:10:00.000Z'),
      headline: 'Good mobility session.',
      highlights: const [
        'Walked with support 15 min',
        'Breakfast completed',
        'Vitals stable',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-16',
      reassuranceState: ReassuranceState.needsAttention,
      generatedAt: DateTime.parse('2026-09-16T05:25:00.000Z'),
      headline: 'Morning medication delayed by 40 min.',
      highlights: const [
        'Delay due to physiotherapy overlap',
        'Rescheduled for tomorrow',
        'No adverse effects noted',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-15',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-15T05:05:00.000Z'),
      headline: 'Settled day.',
      highlights: const [
        'All medications on time',
        'Physiotherapy attended',
        'Heart rate 72 bpm',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-14',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-14T05:00:00.000Z'),
      headline: 'Enjoyed the morning newspaper and tea.',
      highlights: const [
        'Breakfast completed',
        'Read in the lounge',
        'Evening walk 10 min',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-13',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-13T05:10:00.000Z'),
      headline: 'Family video call in the evening.',
      highlights: const [
        'Video call with daughter',
        'Dinner completed',
        'Medication on schedule',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-12',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-12T05:00:00.000Z'),
      headline: 'Few updates logged.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-11',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-11T05:15:00.000Z'),
      headline: 'Physiotherapy progressing well.',
      highlights: const [
        'Strength improved per therapist',
        'Heart rate 70 bpm',
        'Meals completed',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-10',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-10T05:05:00.000Z'),
      headline: 'Calm day.',
      highlights: const [
        'Morning medication taken',
        'Short walk in the corridor',
        'Afternoon rest 1 hr',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-09',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-09T05:10:00.000Z'),
      headline: 'Good appetite and mood.',
      highlights: const [
        'Breakfast and lunch completed',
        'Physiotherapy attended',
        'Vitals stable',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-08',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-08T05:00:00.000Z'),
      headline: 'Routine day.',
      highlights: const [
        'Medication on time',
        'BP 118/76',
        'Evening tea with peers',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-07',
      reassuranceState: ReassuranceState.needsAttention,
      generatedAt: DateTime.parse('2026-09-07T05:20:00.000Z'),
      headline: 'Complained of mild dizziness in the morning.',
      highlights: const [
        'BP checked — 108/68',
        'Doctor reviewed',
        'Advised hydration and rest',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-06',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-06T05:05:00.000Z'),
      headline: 'Recovered well, no further dizziness.',
      highlights: const [
        'BP 118/74',
        'Physiotherapy resumed',
        'Meals completed',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-05',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-05T05:10:00.000Z'),
      headline: 'Steady day.',
      highlights: const [
        'Morning medication taken',
        'Short walk 12 min',
        'Heart rate 74 bpm',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-04',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-04T05:00:00.000Z'),
      headline: 'Quiet day, good rest.',
      highlights: const [
        'All medications on time',
        'Afternoon nap 1.5 hr',
        'Evening vitals stable',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-03',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-03T05:00:00.000Z'),
      headline: 'Limited information available.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-02',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-02T05:10:00.000Z'),
      headline: 'Good day overall.',
      highlights: const [
        'Physiotherapy attended',
        'Breakfast completed',
        'BP 120/78',
      ],
    ),
    DailySummary(
      residentId: 'resident-devendra',
      localDate: '2026-09-01',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-01T05:05:00.000Z'),
      headline: 'Positive start to the month.',
      highlights: const [
        'Medication on schedule',
        'Short garden visit',
        'Heart rate 71 bpm',
      ],
    ),

    // --- Anjali: sample days ---
    DailySummary(
      residentId: 'resident-anjali',
      localDate: '2026-09-19',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-19T05:10:00.000Z'),
      headline: 'Anjali is in good spirits.',
      highlights: const [
        'Breakfast and lunch completed',
        'Attended yoga session',
        'BP within range',
      ],
    ),
    DailySummary(
      residentId: 'resident-anjali',
      localDate: '2026-09-18',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-18T05:05:00.000Z'),
      headline: 'Active morning.',
      highlights: const [
        'Yoga 30 min',
        'Medication taken',
        'Social hour attended',
      ],
    ),
    DailySummary(
      residentId: 'resident-anjali',
      localDate: '2026-09-17',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-17T05:00:00.000Z'),
      headline: 'Settled day.',
      highlights: const [
        'All meals completed',
        'Evening walk 15 min',
        'Vitals stable',
      ],
    ),

    // --- Rajan: sample days ---
    DailySummary(
      residentId: 'resident-rajan',
      localDate: '2026-09-19',
      reassuranceState: ReassuranceState.notEnoughInformation,
      generatedAt: DateTime.parse('2026-09-19T05:00:00.000Z'),
      headline: 'Few updates for Rajan today.',
      highlights: const [],
    ),
    DailySummary(
      residentId: 'resident-rajan',
      localDate: '2026-09-18',
      reassuranceState: ReassuranceState.reassuring,
      generatedAt: DateTime.parse('2026-09-18T05:10:00.000Z'),
      headline: 'Routine day.',
      highlights: const [
        'Medication on time',
        'Breakfast completed',
        'Read in the library',
      ],
    ),
  ];

  static final List<Map<String, dynamic>> _rawCareEvents = [
    // --- Meera: 2026-09-19 ---
    {
      'id': 'evt-m-101',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-19T02:30:00.000Z',
      'recordedAt': '2026-09-19T02:41:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-102',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-19T02:45:00.000Z',
      'recordedAt': '2026-09-19T03:05:00.000Z',
      'visibility': 'family',
      'note': 'Ate well.',
    },
    {
      'id': 'evt-m-103',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Garden walk',
      'status': 'completed',
      'durationMinutes': 22,
      'recordedAt': '2026-09-19T04:20:00.000Z',
      'visibility': 'family',
      'note': 'Walked with the morning group.',
    },
    {
      'id': 'evt-m-104',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Private medication',
      'status': 'taken',
      'scheduledAt': '2026-09-19T05:00:00.000Z',
      'recordedAt': '2026-09-19T05:03:00.000Z',
      'visibility': 'resident_only',
      'note': 'This event must not be exposed to family.',
    },

    // --- Meera: 2026-09-18 ---
    {
      'id': 'evt-m-0918-01',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-18T02:30:00.000Z',
      'recordedAt': '2026-09-18T02:35:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0918-02',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-18T02:45:00.000Z',
      'recordedAt': '2026-09-18T03:10:00.000Z',
      'visibility': 'family',
      'note': 'Finished full portion.',
    },
    {
      'id': 'evt-m-0918-03',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Bhajan session',
      'status': 'completed',
      'durationMinutes': 35,
      'recordedAt': '2026-09-18T05:00:00.000Z',
      'visibility': 'family',
      'note': 'Sang along with the group.',
    },
    {
      'id': 'evt-m-0918-04',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'lunch',
      'status': 'completed',
      'scheduledAt': '2026-09-18T07:30:00.000Z',
      'recordedAt': '2026-09-18T07:55:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0918-05',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Evening medication',
      'status': 'taken',
      'scheduledAt': '2026-09-18T12:30:00.000Z',
      'recordedAt': '2026-09-18T12:33:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Meera: 2026-09-17 ---
    {
      'id': 'evt-m-0917-01',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-17T02:30:00.000Z',
      'recordedAt': '2026-09-17T02:38:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0917-02',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-17T02:45:00.000Z',
      'recordedAt': '2026-09-17T03:08:00.000Z',
      'visibility': 'family',
      'note': 'Ate most of it.',
    },
    {
      'id': 'evt-m-0917-03',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': 20,
      'recordedAt': '2026-09-17T04:45:00.000Z',
      'visibility': 'family',
      'note': 'Knee discomfort noted — 3/10. Adjusted exercises.',
    },
    {
      'id': 'evt-m-0917-04',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'lunch',
      'status': 'completed',
      'scheduledAt': '2026-09-17T07:30:00.000Z',
      'recordedAt': '2026-09-17T07:50:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0917-05',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Rest',
      'status': 'completed',
      'durationMinutes': 60,
      'recordedAt': '2026-09-17T09:00:00.000Z',
      'visibility': 'family',
      'note': 'Stayed indoors in the afternoon.',
    },

    // --- Meera: 2026-09-16 ---
    {
      'id': 'evt-m-0916-01',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-16T02:30:00.000Z',
      'recordedAt': '2026-09-16T02:36:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0916-02',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-16T02:45:00.000Z',
      'recordedAt': '2026-09-16T03:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0916-03',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Art & craft',
      'status': 'completed',
      'durationMinutes': 45,
      'recordedAt': '2026-09-16T05:30:00.000Z',
      'visibility': 'family',
      'note': 'Made a paper flower arrangement.',
    },
    {
      'id': 'evt-m-0916-04',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'lunch',
      'status': 'completed',
      'scheduledAt': '2026-09-16T07:30:00.000Z',
      'recordedAt': '2026-09-16T07:52:00.000Z',
      'visibility': 'family',
      'note': 'Full portion.',
    },
    {
      'id': 'evt-m-0916-05',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'dinner',
      'status': 'completed',
      'scheduledAt': '2026-09-16T13:00:00.000Z',
      'recordedAt': '2026-09-16T13:20:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Meera: 2026-09-15 ---
    {
      'id': 'evt-m-0915-01',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Garden walk',
      'status': 'completed',
      'durationMinutes': 20,
      'recordedAt': '2026-09-15T03:50:00.000Z',
      'visibility': 'family',
      'note': 'Walked with two other residents.',
    },
    {
      'id': 'evt-m-0915-02',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Music therapy',
      'status': 'completed',
      'durationMinutes': 40,
      'recordedAt': '2026-09-15T06:00:00.000Z',
      'visibility': 'family',
      'note': 'Enjoyed old Hindi songs.',
    },
    {
      'id': 'evt-m-0915-03',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-15T02:30:00.000Z',
      'recordedAt': '2026-09-15T02:40:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0915-04',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-15T02:45:00.000Z',
      'recordedAt': '2026-09-15T03:05:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0915-05',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'lunch',
      'status': 'completed',
      'scheduledAt': '2026-09-15T07:30:00.000Z',
      'recordedAt': '2026-09-15T07:48:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Meera: 2026-09-13 (video call day) ---
    {
      'id': 'evt-m-0913-01',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Family video call',
      'status': 'completed',
      'durationMinutes': 25,
      'recordedAt': '2026-09-13T10:30:00.000Z',
      'visibility': 'family',
      'note': 'Spoke with son and grandchildren.',
    },
    {
      'id': 'evt-m-0913-02',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'lunch',
      'status': 'completed',
      'scheduledAt': '2026-09-13T07:30:00.000Z',
      'recordedAt': '2026-09-13T07:55:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-m-0913-03',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Rest',
      'status': 'completed',
      'durationMinutes': 90,
      'recordedAt': '2026-09-13T08:00:00.000Z',
      'visibility': 'family',
      'note': 'Afternoon rest.',
    },

    // --- Meera: 2026-09-11 (BP attention day) ---
    {
      'id': 'evt-m-0911-01',
      'residentId': 'resident-meera',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '138/86',
      'unit': 'mmHg',
      'recordedAt': '2026-09-11T03:45:00.000Z',
      'visibility': 'family',
      'note': 'Slight rise noted. Rechecked at 11:00.',
    },
    {
      'id': 'evt-m-0911-02',
      'residentId': 'resident-meera',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '132/82',
      'unit': 'mmHg',
      'recordedAt': '2026-09-11T05:30:00.000Z',
      'visibility': 'family',
      'note': 'Recheck — improved. Doctor informed as precaution.',
    },
    {
      'id': 'evt-m-0911-03',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-11T02:30:00.000Z',
      'recordedAt': '2026-09-11T02:42:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Meera: 2026-09-09 (festival day) ---
    {
      'id': 'evt-m-0909-01',
      'residentId': 'resident-meera',
      'category': 'activity',
      'activityType': 'Festival decoration',
      'status': 'completed',
      'durationMinutes': 50,
      'recordedAt': '2026-09-09T05:00:00.000Z',
      'visibility': 'family',
      'note': 'Helped decorate the common area.',
    },
    {
      'id': 'evt-m-0909-02',
      'residentId': 'resident-meera',
      'category': 'meal',
      'mealType': 'snack',
      'status': 'completed',
      'scheduledAt': '2026-09-09T09:00:00.000Z',
      'recordedAt': '2026-09-09T09:15:00.000Z',
      'visibility': 'family',
      'note': 'Festive sweets in moderation.',
    },
    {
      'id': 'evt-m-0909-03',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Evening medication',
      'status': 'taken',
      'scheduledAt': '2026-09-09T12:30:00.000Z',
      'recordedAt': '2026-09-09T12:35:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Meera: 2026-09-02 (dehydration attention day) ---
    {
      'id': 'evt-m-0902-01',
      'residentId': 'resident-meera',
      'category': 'vital',
      'vitalType': 'hydration_check',
      'value': 'mild dehydration signs',
      'unit': null,
      'recordedAt': '2026-09-02T06:00:00.000Z',
      'visibility': 'family',
      'note': 'Fluids encouraged. Urine output monitored.',
    },
    {
      'id': 'evt-m-0902-02',
      'residentId': 'resident-meera',
      'category': 'vital',
      'vitalType': 'hydration_check',
      'value': 'stable',
      'unit': null,
      'recordedAt': '2026-09-02T12:00:00.000Z',
      'visibility': 'family',
      'note': 'Evening check stable.',
    },
    {
      'id': 'evt-m-0902-03',
      'residentId': 'resident-meera',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-02T02:30:00.000Z',
      'recordedAt': '2026-09-02T02:45:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Devendra: 2026-09-19 ---
    {
      'id': 'evt-d-201',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': null,
      'recordedAt': '2026-09-19T04:50:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-202',
      'residentId': 'resident-devendra',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'delayed',
      'scheduledAt': '2026-09-19T03:00:00.000Z',
      'recordedAt': '2026-09-19T03:42:00.000Z',
      'visibility': 'family',
      'note': 'Resident was at physiotherapy.',
    },

    // --- Devendra: 2026-09-18 ---
    {
      'id': 'evt-d-0918-01',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': 30,
      'recordedAt': '2026-09-18T04:40:00.000Z',
      'visibility': 'family',
      'note': 'Good session.',
    },
    {
      'id': 'evt-d-0918-02',
      'residentId': 'resident-devendra',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-18T03:00:00.000Z',
      'recordedAt': '2026-09-18T03:05:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-0918-03',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'heart_rate',
      'value': 73,
      'unit': 'bpm',
      'recordedAt': '2026-09-18T05:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Devendra: 2026-09-17 ---
    {
      'id': 'evt-d-0917-01',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Walk with support',
      'status': 'completed',
      'durationMinutes': 15,
      'recordedAt': '2026-09-17T04:30:00.000Z',
      'visibility': 'family',
      'note': 'Walked with support along the corridor.',
    },
    {
      'id': 'evt-d-0917-02',
      'residentId': 'resident-devendra',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-17T02:45:00.000Z',
      'recordedAt': '2026-09-17T03:10:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-0917-03',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '118/76',
      'unit': 'mmHg',
      'recordedAt': '2026-09-17T05:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Devendra: 2026-09-16 (delayed medication attention) ---
    {
      'id': 'evt-d-0916-01',
      'residentId': 'resident-devendra',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'delayed',
      'scheduledAt': '2026-09-16T03:00:00.000Z',
      'recordedAt': '2026-09-16T03:40:00.000Z',
      'visibility': 'family',
      'note': 'Delay due to physiotherapy overlap. No adverse effects.',
    },
    {
      'id': 'evt-d-0916-02',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': 25,
      'recordedAt': '2026-09-16T04:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Devendra: 2026-09-13 ---
    {
      'id': 'evt-d-0913-01',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Family video call',
      'status': 'completed',
      'durationMinutes': 30,
      'recordedAt': '2026-09-13T12:00:00.000Z',
      'visibility': 'family',
      'note': 'Spoke with daughter.',
    },
    {
      'id': 'evt-d-0913-02',
      'residentId': 'resident-devendra',
      'category': 'meal',
      'mealType': 'dinner',
      'status': 'completed',
      'scheduledAt': '2026-09-13T13:00:00.000Z',
      'recordedAt': '2026-09-13T13:25:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Devendra: 2026-09-11 ---
    {
      'id': 'evt-d-0911-01',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'heart_rate',
      'value': 70,
      'unit': 'bpm',
      'recordedAt': '2026-09-11T05:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-0911-02',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': 30,
      'recordedAt': '2026-09-11T04:40:00.000Z',
      'visibility': 'family',
      'note': 'Strength improved per therapist.',
    },

    // --- Devendra: 2026-09-07 (dizziness attention day) ---
    {
      'id': 'evt-d-0907-01',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '108/68',
      'unit': 'mmHg',
      'recordedAt': '2026-09-07T03:30:00.000Z',
      'visibility': 'family',
      'note': 'Mild dizziness reported. Doctor reviewed.',
    },
    {
      'id': 'evt-d-0907-02',
      'residentId': 'resident-devendra',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-07T03:00:00.000Z',
      'recordedAt': '2026-09-07T03:10:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-0907-03',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'hydration_check',
      'value': 'advisory given',
      'unit': null,
      'recordedAt': '2026-09-07T05:00:00.000Z',
      'visibility': 'family',
      'note': 'Advised hydration and rest.',
    },

    // --- Devendra: 2026-09-06 (recovery) ---
    {
      'id': 'evt-d-0906-01',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '118/74',
      'unit': 'mmHg',
      'recordedAt': '2026-09-06T05:00:00.000Z',
      'visibility': 'family',
      'note': 'No further dizziness.',
    },
    {
      'id': 'evt-d-0906-02',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Physiotherapy',
      'status': 'completed',
      'durationMinutes': 20,
      'recordedAt': '2026-09-06T04:30:00.000Z',
      'visibility': 'family',
      'note': 'Resumed gently.',
    },

    // --- Devendra: 2026-09-01 ---
    {
      'id': 'evt-d-0901-01',
      'residentId': 'resident-devendra',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-01T03:00:00.000Z',
      'recordedAt': '2026-09-01T03:06:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-d-0901-02',
      'residentId': 'resident-devendra',
      'category': 'activity',
      'activityType': 'Garden visit',
      'status': 'completed',
      'durationMinutes': 15,
      'recordedAt': '2026-09-01T05:00:00.000Z',
      'visibility': 'family',
      'note': 'Short garden visit.',
    },
    {
      'id': 'evt-d-0901-03',
      'residentId': 'resident-devendra',
      'category': 'vital',
      'vitalType': 'heart_rate',
      'value': 71,
      'unit': 'bpm',
      'recordedAt': '2026-09-01T05:15:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Anjali: sample events ---
    {
      'id': 'evt-a-101',
      'residentId': 'resident-anjali',
      'category': 'activity',
      'activityType': 'Yoga',
      'status': 'completed',
      'durationMinutes': 30,
      'recordedAt': '2026-09-19T03:30:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-a-102',
      'residentId': 'resident-anjali',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-19T02:30:00.000Z',
      'recordedAt': '2026-09-19T02:35:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-a-103',
      'residentId': 'resident-anjali',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-19T02:45:00.000Z',
      'recordedAt': '2026-09-19T03:05:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-a-104',
      'residentId': 'resident-anjali',
      'category': 'vital',
      'vitalType': 'blood_pressure',
      'value': '120/80',
      'unit': 'mmHg',
      'recordedAt': '2026-09-19T04:00:00.000Z',
      'visibility': 'family',
      'note': 'Within range.',
    },
    {
      'id': 'evt-a-0918-01',
      'residentId': 'resident-anjali',
      'category': 'activity',
      'activityType': 'Social hour',
      'status': 'completed',
      'durationMinutes': 45,
      'recordedAt': '2026-09-18T06:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-a-0917-01',
      'residentId': 'resident-anjali',
      'category': 'activity',
      'activityType': 'Evening walk',
      'status': 'completed',
      'durationMinutes': 15,
      'recordedAt': '2026-09-17T11:30:00.000Z',
      'visibility': 'family',
      'note': null,
    },

    // --- Rajan: sample events ---
    {
      'id': 'evt-r-101',
      'residentId': 'resident-rajan',
      'category': 'medication',
      'medicationLabel': 'Morning medication',
      'status': 'taken',
      'scheduledAt': '2026-09-18T02:30:00.000Z',
      'recordedAt': '2026-09-18T02:40:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-r-102',
      'residentId': 'resident-rajan',
      'category': 'meal',
      'mealType': 'breakfast',
      'status': 'completed',
      'scheduledAt': '2026-09-18T02:45:00.000Z',
      'recordedAt': '2026-09-18T03:00:00.000Z',
      'visibility': 'family',
      'note': null,
    },
    {
      'id': 'evt-r-103',
      'residentId': 'resident-rajan',
      'category': 'activity',
      'activityType': 'Reading',
      'status': 'completed',
      'durationMinutes': 60,
      'recordedAt': '2026-09-18T06:00:00.000Z',
      'visibility': 'family',
      'note': 'Read in the library.',
    },
  ];

  // deliberately malformed: null recordedAt, non-standard status — for listRawTimeline validation testing
  static final Map<String, dynamic> _malformedRecord = {
    'id': 'evt-malformed-999',
    'residentId': 'resident-devendra',
    'category': 'meal',
    'mealType': 'lunch',
    'status': 'RECORDED?',
    'recordedAt': null,
    'visibility': 'family',
  };

  static final List<VitalReading> _vitals = [
    VitalReading(
      id: 'v-m-101',
      residentId: 'resident-meera',
      type: 'blood_pressure',
      value: '124/78',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-19T03:30:00.000Z'),
      referenceLabel: 'Within care-plan range',
      visibility: Visibility.residentOnly,
    ),
    VitalReading(
      id: 'v-d-201',
      residentId: 'resident-devendra',
      type: 'heart_rate',
      value: 74,
      unit: 'bpm',
      measuredAt: DateTime.parse('2026-09-19T04:10:00.000Z'),
      referenceLabel: null,
      visibility: Visibility.family,
    ),
    // --- Additional vitals ---
    VitalReading(
      id: 'v-m-0911',
      residentId: 'resident-meera',
      type: 'blood_pressure',
      value: '138/86',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-11T03:45:00.000Z'),
      referenceLabel: 'Slightly elevated — rechecked',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-m-0911b',
      residentId: 'resident-meera',
      type: 'blood_pressure',
      value: '132/82',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-11T05:30:00.000Z'),
      referenceLabel: 'Improved on recheck',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-m-0918',
      residentId: 'resident-meera',
      type: 'heart_rate',
      value: 78,
      unit: 'bpm',
      measuredAt: DateTime.parse('2026-09-18T04:00:00.000Z'),
      referenceLabel: 'Within care-plan range',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-d-0917',
      residentId: 'resident-devendra',
      type: 'blood_pressure',
      value: '118/76',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-17T05:00:00.000Z'),
      referenceLabel: 'Within care-plan range',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-d-0907',
      residentId: 'resident-devendra',
      type: 'blood_pressure',
      value: '108/68',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-07T03:30:00.000Z'),
      referenceLabel: 'Low — dizziness reported',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-d-0906',
      residentId: 'resident-devendra',
      type: 'blood_pressure',
      value: '118/74',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-06T05:00:00.000Z'),
      referenceLabel: 'Stable — recovered',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-a-101',
      residentId: 'resident-anjali',
      type: 'blood_pressure',
      value: '120/80',
      unit: 'mmHg',
      measuredAt: DateTime.parse('2026-09-19T04:00:00.000Z'),
      referenceLabel: 'Within range',
      visibility: Visibility.family,
    ),
    VitalReading(
      id: 'v-a-102',
      residentId: 'resident-anjali',
      type: 'heart_rate',
      value: 76,
      unit: 'bpm',
      measuredAt: DateTime.parse('2026-09-19T04:05:00.000Z'),
      referenceLabel: null,
      visibility: Visibility.family,
    ),
  ];

  static final List<StaffUpdate> _staffUpdates = [
    StaffUpdate(
      id: 'note-m-101',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-19T04:35:00.000Z'),
      authorRole: 'Wellness coordinator',
      text: 'Meera enjoyed the garden after breakfast.',
      mediaUrl: 'https://example.invalid/private-meera-photo.jpg',
      visibility: Visibility.limited,
    ),
    StaffUpdate(
      id: 'note-m-102',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-19T05:00:00.000Z'),
      authorRole: 'Care associate',
      text: 'Private care note not intended for family.',
      mediaUrl: null,
      visibility: Visibility.residentOnly,
    ),
    StaffUpdate(
      id: 'note-d-201',
      residentId: 'resident-devendra',
      createdAt: DateTime.parse('2026-09-19T04:55:00.000Z'),
      authorRole: 'Physiotherapy team',
      text: null,
      mediaUrl: 'https://example.invalid/intentionally-broken-image.jpg',
      visibility: Visibility.family,
    ),
    // --- Additional staff updates ---
    StaffUpdate(
      id: 'note-m-0918',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-18T05:30:00.000Z'),
      authorRole: 'Wellness coordinator',
      text: 'Meera participated enthusiastically in the bhajan session.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
    StaffUpdate(
      id: 'note-m-0917',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-17T05:15:00.000Z'),
      authorRole: 'Physiotherapy team',
      text:
          'Knee discomfort noted during session. Adjusted exercises; resident comfortable afterwards.',
      mediaUrl: null,
      visibility: Visibility.limited,
    ),
    StaffUpdate(
      id: 'note-m-0911',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-11T06:00:00.000Z'),
      authorRole: 'Care associate',
      text:
          'BP slightly elevated in the morning; recheck improved. Doctor informed as precaution.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
    StaffUpdate(
      id: 'note-m-0909',
      residentId: 'resident-meera',
      createdAt: DateTime.parse('2026-09-09T06:30:00.000Z'),
      authorRole: 'Wellness coordinator',
      text:
          'Meera helped decorate the common area for the festival. Lovely to see her engaged.',
      mediaUrl: 'https://example.invalid/meera-festival.jpg',
      visibility: Visibility.limited,
    ),
    StaffUpdate(
      id: 'note-d-0918',
      residentId: 'resident-devendra',
      createdAt: DateTime.parse('2026-09-18T05:30:00.000Z'),
      authorRole: 'Physiotherapy team',
      text: 'Good physiotherapy session. Mobility improving steadily.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
    StaffUpdate(
      id: 'note-d-0916',
      residentId: 'resident-devendra',
      createdAt: DateTime.parse('2026-09-16T05:00:00.000Z'),
      authorRole: 'Care associate',
      text:
          'Morning medication delayed due to physiotherapy overlap. No adverse effects.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
    StaffUpdate(
      id: 'note-d-0907',
      residentId: 'resident-devendra',
      createdAt: DateTime.parse('2026-09-07T05:30:00.000Z'),
      authorRole: 'Staff nurse',
      text:
          'Devendra reported mild dizziness in the morning. BP 108/68. Doctor reviewed and advised hydration and rest.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
    StaffUpdate(
      id: 'note-a-0919',
      residentId: 'resident-anjali',
      createdAt: DateTime.parse('2026-09-19T05:00:00.000Z'),
      authorRole: 'Wellness coordinator',
      text: 'Anjali continues to enjoy the yoga sessions. Very consistent.',
      mediaUrl: null,
      visibility: Visibility.family,
    ),
  ];
  Future<void> _wait([int minMs = 220, int spreadMs = 380]) => Future.delayed(
    // Duration(milliseconds: minMs + Random().nextInt(spreadMs)),
    Duration(milliseconds: 440),
  );

  Future<ApiEnvelope<List<Resident>>> listResidents() async {
    await _wait();
    return ApiEnvelope(data: List.of(_residents), generatedAt: DateTime.now());
  }

  Future<ApiEnvelope<Resident>> getResident(String residentId) async {
    await _wait();
    final r = _residents.where((e) => e.id == residentId).firstOrNull;
    if (r == null) {
      throw MockApiException('Resident not found', 404, 'RESIDENT_NOT_FOUND');
    }
    return ApiEnvelope(data: r, generatedAt: DateTime.now());
  }

  Future<ApiEnvelope<DailySummary?>> getDailySummary(String residentId) async {
    await _wait();
    final s = _summaries.where((e) => e.residentId == residentId).firstOrNull;
    return ApiEnvelope(data: s, generatedAt: DateTime.now());
  }

  Future<ApiEnvelope<List<CareEvent>>> listCareEvents(String residentId) async {
    await _wait();
    final events = _rawCareEvents
        .where((j) => j['residentId'] == residentId)
        .map((j) => CareEvent.tryFromJson(j))
        .whereType<CareEvent>()
        .toList();
    return ApiEnvelope(data: events, generatedAt: DateTime.now());
  }

  /// Raw, possibly-malformed records — caller must validate before rendering.
  Future<ApiEnvelope<List<Map<String, dynamic>>>> listRawTimeline(
    String residentId,
  ) async {
    await _wait();
    final all = [..._rawCareEvents, _malformedRecord];
    return ApiEnvelope(
      data: all.where((j) => j['residentId'] == residentId).toList(),
      generatedAt: DateTime.now(),
    );
  }

  Future<ApiEnvelope<List<VitalReading>>> listVitals(String residentId) async {
    await _wait(350, 650);
    if (_vitalsIncident) {
      throw MockApiException(
        'Vitals service is temporarily unavailable',
        503,
        'VITALS_UNAVAILABLE',
      );
    }
    return ApiEnvelope(
      data: _vitals.where((v) => v.residentId == residentId).toList(),
      generatedAt: DateTime.now(),
    );
  }

  Future<ApiEnvelope<List<StaffUpdate>>> listStaffUpdates(
    String residentId,
  ) async {
    await _wait();
    return ApiEnvelope(
      data: _staffUpdates.where((s) => s.residentId == residentId).toList(),
      generatedAt: DateTime.now(),
    );
  }

  Future<ApiEnvelope<CheckInRequest>> createCheckInRequest(
    CheckInRequestInput input,
  ) async {
    await _wait(500, 500);
    if (input.reason.trim().isEmpty) {
      throw MockApiException('A reason is required', 422, 'INVALID_REASON');
    }
    return ApiEnvelope(
      data: CheckInRequest(
        residentId: input.residentId,
        reason: input.reason,
        urgency: input.urgency,
        id: 'check-${DateTime.now().millisecondsSinceEpoch}',
        createdAt: DateTime.now(),
        status: 'received',
      ),
      generatedAt: DateTime.now(),
    );
  }

  void setVitalsIncident(bool on) =>
      _vitalsIncident = on; // only flip when an official bulletin says to
}
